export default Object.freeze({
    SET_POKEMONS: 'SET_POKEMONS',
    INIT_POKEMONS: 'INIT_POKEMONS',
    SET_PAGINATION: 'SET_PAGINATION',
    SET_ERROR: 'SET_POKEMONS_ERROR',
    IS_LOADING: 'IS_POKEMONS_LOADING',
    ADD_FILTER: 'ADD_FILTER',
    REMOVE_FILTER: 'REMOVE_FILTER',
    INIT_FILTERS: 'INIT_FILTERS'
})