export default Object.freeze({
    SET_POKEMON: 'SET_POKEMON',
    INIT_POKEMON: 'INIT_POKEMON',
    SET_POKEMON_ID: 'SET_POKEMON_ID',
    SET_POKEMON_ERROR: 'SET_POKEMON_ERROR',
    IS_LOADING: 'IS_POKEMON_LOADING',
    INIT_LOADING: 'INIT_LOADING'
})